name: Run Golf Leaderboard Scraper

on:
  schedule:
    - cron: '*/20 * * * 4'
    - cron: '*/20 * * * 5'
    - cron: '*/20 * * * 6'
    - cron: '*/20 * * * 0'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest # Use a Linux environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          cd pga-golf-scraper  # Change directory to pga-golf-scraper
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Scraper
        run: |
          cd pga-golf-scraper  # Change directory to pga-golf-scraper
          python scraper.py  # Run scraper.py from pga-golf-scraper/

      - name: Upload SQLite Database
        uses: actions/upload-artifact@v4
        with:
          name: pga-data
          path: pga-golf-scraper/pga-data.db # Upload pga-data.db from pga-golf-scraper/
